### ISSUE TITLE
No controller input code

### ISSUE THREAD

**Issue by EthanWyrick** [theagencyteam3021/FRC2019#3]
we need it

**Comment by rajpabari** [comment]
* Start driving with arcade for new driving, not as good for old drivers
 * You want all functions to be on the front
 * Flip switch to change styles ?
 * Tank drive has 2 joysucks - bad and inaccurate , clunky, oversteering, diff to aim
 *  Arcade, left is throttle,  squared inputs,  0 - 1 instead of this, make it a squared graph on 
 * both inputs, slow and precise, and it can go high speed
 * Right turns it (only l-r) and left controls power (only u-d), minimum input as well, apply atl 10% as the floor
 * Robot wont do anything at 3%

**Comment by kevinmeziere** [comment]
This might help.

https://wpilib.screenstepslive.com/s/currentCS/m/java/l/599739-running-commands-on-joystick-input

**Comment by EthanWyrick** [comment]
https://first.wpi.edu/FRC/roborio/beta/docs/java/edu/wpi/first/wpilibj/XboxController.html#XboxController-int-
